config/routes.rb
Rails.application.routes.draw do

  #active_admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #split dashboard (AB tests results)
  get "/split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request| request.env['warden'].authenticated? }
  get "/split", to: redirect('/admin')

  #website
  resources :contacts, only: [:create, :show]
  root 'landing#index'
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates_presence_of :name, :email, :text

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout false

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      finished('header_title') #AB test convertion
      render :show
    else
      render :new
    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :text)
    end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @contact = Contact.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/contacts/_form.html.erb
<h4>Contact form:</h4>

<%= form_for(@contact, :remote => true, "data-type" => :json) do |f| %>
  <% if @contact.errors.any? %>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit value: t('landing_page.send_button')%>
  </div>
<% end %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.text %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
Success

app/views/landing/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      <%= ab_test 'header_title', 'Landing page', 'Landing pages for FREE', 'Your first landing page in seconds!' %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'contacts/form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandingPage</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>